spring:
  application:
    name: goodbite

  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

server:
  port: 443
  ssl:
    enabled: true
    key-store: /app/api.goodbite.site.p12
    key-store-password: ${SSL_KEY}
    key-store-type: PKCS12
    key-alias: goodbite

publicdata:
  api:
    key: ${PUBLIC_DATA_KEY}
    url: https://api.odcloud.kr/api/nts-businessman/v1/status


logging:
  level:
    root: INFO
    org.springframework: INFO
    com.sparta.goodbite.aspect: DEBUG