spring:
  application:
    name: goodbite

  profiles:
    active: test

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# WebSocket 설정
server:
  port: 8080

#공공데이터
publicdata:
  api:
    key: ${PUBLIC_DATA_KEY}
    url: https://api.odcloud.kr/api/nts-businessman/v1/status