spring:
  application:
    name: goodbite

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  
  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    region:
      auto: false
    stack:
      auto: false

server:
  port: 8080
  ssl:
    enabled: false

logging:
  level:
    root: INFO