@baseUrl=http://localhost:8080/owners
@ownerId=2
### 회원가입
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "testowner1@email.com",
  "nickname": "가게1",
  "password": "Passw0rd!",
  "phoneNumber": "010-0001-0000",
  "businessNumber": "dsf446s1242342"
}

### 회원정보조회
GET {{baseUrl}}/{{ownerId}}

### 회원정보수정-닉네임
PATCH {{baseUrl}}/{{ownerId}}/nickname
Content-Type: application/json

{
  "newNickname": "가게2"
}

### 회원정보수정-전화번호
PATCH {{baseUrl}}/{{ownerId}}/phone-number
Content-Type: application/json

{
  "newPhoneNumber": "010-1111-0000"
}

### 회원정보수정-비밀번호
PATCH {{baseUrl}}/{{ownerId}}/password
Content-Type: application/json

{
  "currentPassword": "Passw0rd!",
  "newPassword": "Passw0rd!@"
}

### 회원정보수정-사업자번호
PATCH {{baseUrl}}/{{ownerId}}/business-number
Content-Type: application/json

{
  "newBusinessNumber": "sdfgsdfgsdgg1234"
}

### 회원탈퇴
DELETE {{baseUrl}}/{{ownerId}}