@baseUrl=http://localhost:8080/owners

### 회원가입
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "testowner2@email.com",
  "nickname": "가게2",
  "password": "Passw0rd!",
  "phoneNumber": "010-0001-2200",
  "businessNumber": "3212653012"
}

### 회원정보조회
GET {{baseUrl}}

### 회원정보수정-닉네임
PATCH {{baseUrl}}/nickname
Content-Type: application/json

{
  "newNickname": "가게0001"
}

### 회원정보수정-전화번호
PATCH {{baseUrl}}/phone-number
Content-Type: application/json

{
  "newPhoneNumber": "010-1012-0000"
}

### 회원정보수정-비밀번호
PATCH {{baseUrl}}/password
Content-Type: application/json

{
  "currentPassword": "Passw0rd!",
  "newPassword": "Passw0rd!!"
}

### 회원정보수정-사업자번호
PATCH {{baseUrl}}/business-number
Content-Type: application/json

{
  "newBusinessNumber": "7838601715"
}

### 회원탈퇴
DELETE {{baseUrl}}